version: '3'

networks:
  bug-stalker-network:
    driver: bridge

services:
  client:
    container_name: bug-stalker-client
    restart: always
    build: ./client
    ports:
      - 4200:4200
    networks:
      - bug-stalker-network
  server:
    container_name: bug-stalker-server
    restart: always
    build: ./server
    ports:
      - 5000:5000
    networks:
      - bug-stalker-network
